bind_addr: 0.0.0.0:8080
direktiv_addr: prod.direktiv.io
insecure_skip_verify: true
routes:
  - alias: html
    namespace: html-test
    token: "v4.token"
  - alias: json
    namespace: json-test
    token: "v4.token"