apiVersion: v1
kind: ConfigMap
metadata:
  name: dproxy-cfg-cm
data:
  config.yaml: |
      bind_addr: 0.0.0.0:8080
      direktiv_addr: prod.direktiv.io
      routes:
        - alias: html
          namespace: html-test
          token: "v4.token"
        - alias: json
          namespace: json-test
          token: "v4.token"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dproxy
  labels:
    app: dproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dproxy
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        app: dproxy
    spec:
      volumes:
      - name: dproxyconf
        configMap:
          name: dproxy-cfg-cm
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532        
        runAsGroup: 65532
      containers:
        - name: dproxy
          image: gcr.io/dproxy:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: dproxyconf
            mountPath: "/config"
            readOnly: false
---
apiVersion: v1 
kind: Service
metadata:
  name: dproxy-service
spec:
  selector:
    app: dproxy
  ports:
    - port: 8080
---
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: dproxy-route
spec:
  http:
  - name: dproxy-receiver
    match:
      hosts:
      - prod.direktiv.io
      paths:
      - "/dproxy/*"
    backends:
    - serviceName: dproxy-service
      servicePort: 8080